export const COPY_EN = {
  hubs: {
    statusOpen: "OPEN",
    statusComingSoon: "COMING SOON",
    workspacePreview: "Workspace-scoped preview",
    overview: "Overview",
    howItWorks: "How it works",
    whatYouCanDo: "What you can do",
    whatsNext: "What’s next",
    notifyMe: "Notify me",
    notifyToast: "Got it — we'll notify you.",
    whatsNextBody: "We're polishing this hub. Tap Notify me to get updates when it goes live.",
    open: "Open",
    catalogTitle: "Hubs",
    catalogSubtitle:
      "Explore Gigaviz hubs. Open items take you directly to the hub; coming soon items let you request early access.",
  },
  helper: {
    title: "Gigaviz Helper",
    subtitle: "AI assistant for chat, copy, and summaries.",
    conversations: "Conversations",
    new: "New",
    searchPlaceholder: "Search conversations",
    noConversations: "No conversations yet.",
    noMessages: "No messages yet.",
    selectOrCreate: "Select or create a conversation.",
    loading: "Loading...",
    modes: { chat: "Chat", copy: "Copy", summary: "Summary" },
    composerPlaceholder: "Write a prompt or instructions...",
    send: "Send",
    workspaceControls: "Workspace Controls",
    todaysBudget: "Today’s budget",
    monthlyCap: "Monthly cap",
    allowAutomation: "Allow automation",
    automationDesc: "Send commands to external workflows.",
    quickPromptsTitle: "Quick prompts",
    quickPrompts: ["Summarize chat", "Write a polite reply", "Draft an ad caption"],
    tipsTitle: "Tips",
    tips: [
      "Don't share secrets inside conversations.",
      "Use Summary mode for quick digests.",
      "Auto provider picks an available model.",
    ],
    viewAllHubs: "View all hubs →",
    badges: { mode: "Mode", provider: "Provider" },
    senderLabels: { user: "You", assistant: "Assistant" },
  },
};
