export const COPY_EN = {
  hubs: {
    statusOpen: "OPEN",
    statusComingSoon: "COMING SOON",
    workspacePreview: "Workspace-scoped preview",
    overview: "Overview",
    howItWorks: "How it works",
    whatYouCanDo: "What you can do",
    whatsNext: "What's next",
    notifyMe: "Notify me",
    notifyToast: "Got it — we'll notify you.",
    whatsNextBody: "We're polishing this hub. Tap Notify me to get updates when it goes live.",
    open: "Open",
    catalogTitle: "Hubs",
    catalogSubtitle:
      "Explore Gigaviz hubs. Open items take you directly to the hub; coming soon items let you request early access.",
  },
  helper: {
    title: "Gigaviz Helper",
    subtitle: "AI assistant for chat, copy, and summaries.",
    conversations: "Conversations",
    new: "New",
    newConversation: "New conversation",
    searchPlaceholder: "Search conversations...",
    noConversations: "No conversations yet.",
    noMessages: "No messages yet.",
    selectOrCreate: "Select or create a conversation.",
    loading: "Loading...",
    modes: { chat: "Chat", copy: "Copy", summary: "Summary" },
    modeDescriptions: {
      chat: "General-purpose conversation",
      copy: "Generate marketing copy",
      summary: "Summarize text or conversations",
    },
    providers: {
      auto: "Auto",
      openai: "OpenAI",
      gemini: "Gemini",
      anthropic: "Anthropic",
      local: "Local",
    },
    composerPlaceholder: "Write a prompt or instructions...",
    composerHint: "Shift+Enter for newline",
    send: "Send",
    clear: "Clear",
    workspaceControls: "Workspace Controls",
    todaysBudget: "Today's budget",
    monthlyCap: "Monthly cap",
    manage: "Manage",
    manageBudgetTitle: "Budget Management",
    manageBudgetDesc: "Token limits and budget controls coming soon.",
    allowAutomation: "Allow automation",
    automationDesc: "Enable AI to execute external workflows.",
    automationConfirmTitle: "Enable Automation?",
    automationConfirmDesc: "This allows the assistant to trigger external actions.",
    confirm: "Confirm",
    cancel: "Cancel",
    quickPromptsTitle: "Quick prompts",
    quickPrompts: [
      "Summarize this chat",
      "Write a polite reply",
      "Draft an ad caption",
      "Explain this concept",
    ],
    tipsTitle: "Tips",
    tips: [
      "Don't share secrets inside conversations.",
      "Use Summary mode for quick digests.",
      "Auto provider picks an available model.",
    ],
    viewAllHubs: "View all hubs →",
    badges: { mode: "Mode", provider: "Provider" },
    senderLabels: { user: "You", assistant: "Assistant" },
    emptyState: {
      title: "Start a conversation",
      description: "Ask a question, generate copy, or summarize content.",
      suggestedPrompts: [
        { label: "Draft a welcome email", prompt: "Draft a friendly welcome email for new users" },
        { label: "Summarize key points", prompt: "Summarize the key points from this text" },
        { label: "Write ad copy", prompt: "Write compelling ad copy for our product launch" },
        { label: "Explain a concept", prompt: "Explain this technical concept in simple terms" },
      ],
    },
    createFirst: "Create your first conversation",
    rename: "Rename",
    delete: "Delete",
    deleteConfirmTitle: "Delete Conversation?",
    deleteConfirmDesc: "This action cannot be undone.",
    copied: "Copied to clipboard",
    processing: "Processing...",
    updated: "Updated",
    tokens: "tokens",
  },
};
