name: build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # aktifkan corepack agar pnpm bisa dipakai
      - name: Enable Corepack
        run: corepack enable

      # pastikan versi pnpm sama dgn packageManager (9.7.0)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0

      # kadang runner perlu PATH ini supaya 'pnpm' kebaca
      - name: Add pnpm to PATH
        run: echo "$(pnpm bin -g)" >> $GITHUB_PATH

      # install semua deps workspace (lockfile wajib sinkron)
      - name: Install deps (workspace)
        run: pnpm -w install --frozen-lockfile

      # generate prisma client (kalau paket db ada prisma)
      - name: Prisma generate
        run: pnpm -C packages/db prisma generate

      # typecheck & build app
      - name: Typecheck web
        run: pnpm -C apps/web typecheck

      - name: Build web
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: pnpm -C apps/web build
