name: build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'                 # cache pnpm lockfile

      - name: Enable Corepack (use packageManager)
        run: |
          corepack enable                # aktifkan corepack
          corepack prepare pnpm@9.7.0 --activate  # pastikan 9.7.0

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Prisma generate
        run: pnpm -C packages/db prisma generate

      - name: Typecheck
        run: pnpm -C apps/web typecheck

      - name: Build web
        run: pnpm -C apps/web build
